# Generated by Django 4.0.4 on 2022-05-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orders_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=111)),
                ('desc', models.TextField(max_length=11111)),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'orders'},
        ),
    ]
