# Generated by Django 4.0.4 on 2022-05-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password2',
        ),
    ]
