# Generated by Django 4.0.4 on 2022-05-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
